# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 241f22f9efbe95e9de296e36ad9dd561baa545ccfc2add16eee8eed36fb13493d1bc801e35a4466f5dceeea19da02c69a6fce12b03dd47601c861337ffdc50af

test:
  secret_key_base: f735094116c77626291ad1fac1de91e9c865749ee3cd6c21aa11260dc411fd0c55d4173478fe9ef5f2b899a0f35ed9f5556819bcc039124aa7196cfaaa868ccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
